# Generated by Django 3.1.1 on 2020-10-28 12:58

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('todo_app', '0003_todo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('mobileNumber', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31, unique=True)),
                ('rank', models.CharField(choices=[('Gold', 'Gold membership'), ('Silver', 'Silver membership'), ('Basic', 'Basic membership')], default='Basic', max_length=32)),
            ],
        ),
    ]
