# Generated by Django 3.1.1 on 2020-10-28 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
