# Generated by Django 3.1.1 on 2020-12-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_auto_20201216_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
